units_type: character
feature_source: kaldi
feature_type: fbank
data:
    name: aishell
    vocab: egs/aishell/data/vocab_new
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: True
    max_input_length: 500  # data_loader output T frames in (n * T * D)
    max_target_length: 50
    batch_size: 8
    short_first: True
    shuffle: True
    train: /home1/meichaoyang/workspace/git/kws/egs/aishell1/data/train
    dev: /home1/meichaoyang/workspace/git/kws/egs/aishell1/data/dev
    test: /home1/meichaoyang/workspace/git/kws/egs/aishell1/data/test
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 320
        output_size: 320
        n_layers: 3
        bidirectional: True
        ctc_weight: 0.0
        number_of_ctc_epochs: 10
    dec:
        type: lstm
        hidden_size: 512
        output_size: 320
        n_layers: 1
        ce_weight: 0.0
        number_of_ce_epochs: 10
    joint:
        input_size: 640
        inner_size: 512
    vocab_size: 4232
    share_weight: False
    feature_dim: 320
    dropout: 0.3
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    gpus: "1"
    epochs: 60
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: 3blstm_320henc_1l512dec
optim:
    type: adam
    lr: 0.0005
    momentum: 0.9
    decay_ratio: 1.0
    weight_decay: 0.00001
    begin_to_adjust_lr: 10
