units_type: character
feature_source: kaldi
feature_type: fbank
data:
    name: magic
    vocab: egs/aishell/data/magic_aishell_vocab
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 500
    max_target_length: 50
    batch_size: 32
    short_first: True
    shuffle: True
    train: /home1/meichaoyang/dataset/magictang/rnn_t/train
    dev: /home1/meichaoyang/dataset/magictang/rnn_t/dev
    test: /home1/meichaoyang/workspace/git/kws/egs/aishell1/data/test_40_bin
model:
    type: ctc
    enc:
        type: lstm
        hidden_size: 320
        output_size: 320
        n_layers: 4
        bidirectional: True
    vocab_size: 5455
    share_weight: False
    feature_dim: 160
    dropout: 0.3
training:
    load_model: False
    seed: 2019
    show_interval: 1
    save_model: 4blstm_320ctc_gpu2_retrain
evaling:
    load_model: egs/magic/exp/transducer/4blstm_320_lstm512_gpu1/4blstm_320_lstm512_gpu1.epoch24.chkpt
    beam_size: 8
    nbest: 6
    lm_weight: 0.0
    state_beam: 3.0
    expand_beam: 3.0
    gpus: "2"
    show_interval: 10
    seed: 2019
optim:
    type: sgd
    lr: 0.0008
    momentum: 0.9
    decay_ratio: 0.8
    weight_decay: 0
    begin_to_adjust_lr: 10


