units_type: character
feature_source: kaldi
feature_type: fbank
data:
    name: magic
    vocab: egs/aishell/data/magic_aishell_vocab
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 700
    max_target_length: 40
    batch_size: 8
    short_first: True
    shuffle: True
    train: /home1/meichaoyang/dataset/magictang/rnn_t/train
    dev: /home1/meichaoyang/dataset/magictang/rnn_t/dev
    test: /home1/meichaoyang/dataset/magictang/rnn_t/test
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 320
        output_size: 320
        n_layers: 4
        bidirectional: True
    dec:
        type: lstm
        hidden_size: 512
        output_size: 320
        n_layers: 1
        input_sorted: True
    joint:
        input_size: 640
        inner_size: 512
        type: concat # type [sum | concat]
    vocab_size: 5455
    share_weight: False
    feature_dim: 160
    dropout: 0
training:
    load_model: False
    seed: 2019
    show_interval: 1
    save_model: 4blstm_320_lstm512_gpu1
evaling:
    load_model: egs/magic/exp/transducer/4blstm_320_lstm512_gpu1/4blstm_320_lstm512_gpu1.epoch24.chkpt
    beam_size: 8
    nbest: 6
    lm_weight: 0.0
    state_beam: 3.0
    expand_beam: 3.0
    gpus: "2"
    show_interval: 10
    seed: 2019
optim:
    type: sgd
    lr: 0.0008
    momentum: 0.9
    decay_ratio: 0.8
    weight_decay: 0
    begin_to_adjust_lr: 10


